In [3]:
import numpy as np
v = np.array([[1, 2], [3, 4]])
np.var(v)

1.25

In [5]:
np.var(v, axis=0)

array([1., 1.])

In [6]:
a = np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
np.var(a)

2.9166666666666665

In [9]:
np.var(a, axis=1)

array([0.25, 0.25, 0.25])

In [45]:
x = np.array([0.5, 6.2, 3.0, 1.7])
bins = np.array([ 0.0,11,12])

In [46]:
inds = np.digitize(x, bins)
inds

array([1, 1, 1, 1], dtype=int64)

In [44]:
x = np.array([0.2, 6.4, 3.0, 1.6])
for n in range(x.size):
    print(n)

0
1
2
3


In [47]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
b1 = np.where(a==3)[0]
b1

array([1], dtype=int64)